apiVersion: apps/v1
kind: Deployment

metadata:
  name: production-cicd-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: production-cicd-app

  template:
    metadata:
      labels:
        app: production-cicd-app

    spec:
      containers:
        - name: production-cicd-app
          image: 637423165688.dkr.ecr.eu-north-1.amazonaws.com/production-cicd-platform:97806c22142c6e331f15a3baad0f788d69b64bb6
          ports:
            - containerPort: 8000
